name: SnykSync Runner
on:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Initiate Caches
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: go build .

      - name: Run SnykSync
        env:
          SS_GHTOKEN: ${{ secrets.SS_GHTOKEN }}
          SS_GHORG: ${{ secrets.SS_GHORG }}
          SS_SNYKTOKEN: ${{ secrets.SS_SNYKTOKEN }}
          SS_SNYKORG: ${{ secrets.SS_SNYKORG }}
          SS_SNYKINTID: ${{ secrets.SS_SNYKINTID }}
        run: ./snyksync